### ISSUE TITLE
Sample data is not working

### ISSUE THREAD

**Issue by mcpierce** [imsweb/x12-parser#20] opened 2020-02-06 15:23 UTC
I'm building an integration component for my work project using the x12-parser library. I was looking for a decent 837 document example with a lot of data and copied the file [x12_many_claims.txt](https://github.com/imsweb/x12-parser/blob/master/src/test/resources/837_5010/x12_many_claims.txt) for use.

But when the X12Parser class processes the file, it fails with errors, including:

```
Unable to find a matching segment format in loop 2310B
NM1 in loop 2310B is required but not found
Unable to find a matching segment format in loop 2320
OI in loop 2320 is required but not found
```
There are a total of 32 errors, no fatal errors, when X12Reader parses this file.

Is it expected to be a usable example file for testing the parser?

**Comment by angelaszek** [comment] 2020-02-06 16:29
When I test with that file here I am not getting any errors or fatal errors so I am not sure what the source of the problem is.

**Comment by nddipiazza** [comment] 2020-06-11 19:58
@mcpierce  please provide steps to reproduce, or close this issue. thanks!

**Closed** 2021-06-29 13:37 UTC
